fix: display user name in posts
Sanchitbajaj02/palettegram pull request #119
Opened 2024-01-03 14:09 UTC by Vidip-Ghosh

## Related Issue

Closes #90 

## Description

Earlier post ID was showing in place of username. So, I fixed that by getting current signed in user. 

## Screenshots

<img width="1205" alt="Screenshot 2024-01-03 at 19 30 08" src="https://github.com/Sanchitbajaj02/palettegram/assets/91741581/8b81d449-2fae-49d8-84da-2c15babf472c">

2024-01-03 18:53 UTC, Sanchitbajaj02 requested changes

2024-01-03 18:53 UTC, Sanchitbajaj02 commented on src/components/core/posts/SinglePost.tsx
> +        <h5 className="font-medium text-md">{user.name}</h5>
I think it should be according to the user post and not according to the current user. One solution is that you are getting the `accountId` from the singlePost object, pass this id to the api which fetches the username/fullName

2024-01-07 10:38 UTC, Vidip-Ghosh commented
<img width="1680" alt="Screenshot 2024-01-07 at 15 48 41" src="https://github.com/Sanchitbajaj02/palettegram/assets/91741581/a6c7f918-477b-409e-abc5-33e71a3f7814">
The changes made.

2024-01-07 11:53 UTC, Sanchitbajaj02 approved these changes

2024-01-07 11:55 UTC, merged