fix: start your journey button fixed
Sanchitbajaj02/palettegram pull request #135
Opened 2024-01-06 13:10 UTC by sumanjeet0012

## Related Issue

fix: #134 
## Description

Now the 'start your journey' button changes to 'Checkout your feed' button and redirects logged in unverified users to feed page.

## Screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/78401409/b668534c-7cd7-440b-8f25-8bdbf6809c0e)

2024-01-06 13:12 UTC, Sanchitbajaj02 requested changes

2024-01-06 13:12 UTC, Sanchitbajaj02 commented on src/components/pages/home/index.tsx
> +              {state?.creds.userId && state?.creds.userId !== '' ? (
isn't isVerified not coming there?

2024-01-07 18:34 UTC, sumanjeet0012 commented
what changes should I make in this issue

2024-01-07 18:54 UTC, Sanchitbajaj02 commented
> what changes should I make in this issue

it is written above with the marked line number

2024-01-07 20:20 UTC, sumanjeet0012 commented
I am 

> > what changes should I make in this issue
> 
> it is written above with the marked line number

2024-01-07 20:28 UTC, sumanjeet0012 commented
@Sanchitbajaj02 This is just a single line code change , I am expecting clear instructions from you about what should I do in this issue.

If this code change is correct accept the PR.
If something needs to be done just give me clear instructions I will do it as soon as possible.
and if this issue is not important then I will start working on some other issues.

 Just provide clear instructions .......

2024-01-08 08:47 UTC, Sanchitbajaj02 commented
I am approving and merging this PR for now. If anyone faces any issue related to verification, you have to handle it

2024-01-08 08:48 UTC, merged

2024-01-08 11:51 UTC, sumanjeet0012 commented
> I am approving and merging this PR for now. If anyone faces any issue related to verification, you have to handle it

Yes, of course