fix: individual post view added
Sanchitbajaj02/palettegram pull request #165
Opened 2024-01-10 14:53 UTC by ani2607

## Related Issue
#121 

## Description

I just created a route of <base_url>/post/postId  which substantially created a page for rendering the individual post with the specific post id.

## Screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/136100597/57e6af7b-5b6d-4e1a-a985-b8ec08013e4d)
![image](https://github.com/Sanchitbajaj02/palettegram/assets/136100597/b6b00642-590a-421b-b1dd-510abd40bd5b)

2024-01-10 17:14 UTC, Sanchitbajaj02 requested changes

2024-01-10 17:14 UTC, Sanchitbajaj02 commented on src/components/core/post/index.tsx
Couldn't the Singlepost.tsx be used there?

2024-01-10 17:14 UTC, Sanchitbajaj02 commented
@ani2607 PR is reviewed. Please also remove the merge conflicts as well

2024-01-10 17:20 UTC, ani2607 commented on src/components/core/post/index.tsx
Yaa! would update.

2024-01-10 20:52 UTC, ani2607 commented on src/components/core/post/index.tsx
Yaa! Updated , please check

2024-01-11 04:31 UTC, Sanchitbajaj02 approved these changes

2024-01-11 04:49 UTC, Sanchitbajaj02 approved these changes

2024-01-11 04:51 UTC, Sanchitbajaj02 commented
@ani2607 PR reviewed. Please resolve the merge conflicts of yarn.lock.
To fix this issue, delete the current yarn.lock and generate new one and then push

2024-01-12 15:30 UTC, Sanchitbajaj02 approved these changes

2024-01-12 15:30 UTC, merged