refactor: createPost handler
Sanchitbajaj02/palettegram pull request #177
Opened 2024-01-15 07:16 UTC by Girishbari

## Related Issue

**Refactored : handleSubmit handler in CreatePost**
## Description

earlier create post component would send toastify and resets the states even if the post was not able to save in the database, **made a negation in if condition** so that toastify and state would not able to reset if the problem has occurred during saving of post in DB

2024-01-15 11:33 UTC, IrfanshaikH-7 commented
Pakage lock !?😅 Yarn should've stoped it tho !

2024-01-15 11:46 UTC, Sanchitbajaj02 requested changes

2024-01-15 11:46 UTC, Sanchitbajaj02 commented on .yarnrc.yml
remove this file

2024-01-15 11:46 UTC, Sanchitbajaj02 commented on package-lock.json
remove this

2024-01-15 11:47 UTC, Sanchitbajaj02 commented
@Girishbari Suggested some changes, please improve. Also create an issue first and linked that to this PR

2024-01-15 15:52 UTC, Girishbari reviewed
removed yarnrm.yml and package-lock.json

2024-01-16 07:48 UTC, Sanchitbajaj02 approved these changes

2024-01-16 07:51 UTC, merged