fix: user-id is clear through logout function
Sanchitbajaj02/palettegram pull request #179
Opened 2024-01-15 11:34 UTC by IamSudhir-Kumar

## Related Issue
#175 

## Description

1. Modified `logoutUser` function in response to a potential issue.
2. Removed explicit session ID argument in the `deleteSession` method call.
3. Improved clarity and compatibility by using `deleteSession` without specifying a session ID.
4. Ensured a straightforward and effective logout process by clearing the current session. 

## Screenshots

2024-01-15 11:44 UTC, Sanchitbajaj02 requested changes

2024-01-15 11:44 UTC, Sanchitbajaj02 commented on src/backend/auth.api.ts
> +    const deletedSession = await account.deleteSession();
The session is clearing from the appwrite but not clearing from the cookies. Try to implement it in the redux where we are updating the cookies

2024-01-16 07:55 UTC, Sanchitbajaj02 requested changes

2024-01-16 07:55 UTC, Sanchitbajaj02 commented on src/redux/reducers/authReducer.ts
> +import { setCookie } from "cookies";
you cannot directly access the cookies in nextjs client. That's why added the nookies package.

2024-01-16 07:55 UTC, Sanchitbajaj02 commented on src/redux/reducers/authReducer.ts
> +      try {
try catch idea is good. Is this tested?

2024-01-16 07:55 UTC, Sanchitbajaj02 commented on src/redux/reducers/authReducer.ts
> +        setCookie(null, "userId", "");
There is a function called destroy cookies in nookies. You should implement that.

2024-01-20 06:12 UTC, thevirengarg commented
@IamSudhir-Kumar What's the progress on the changes requested?

2024-01-22 17:32 UTC, Girishbari commented
@IamSudhir-Kumar #213 this was the changes

2024-01-22 19:35 UTC, closed without merging