fix: currentUser issue169
Sanchitbajaj02/palettegram pull request #196
Opened 2024-01-18 08:05 UTC by IrfanshaikH-7

## Related Issue
Issue #169 

## Description:
Fix the issue where in user profile, it was previously rendering currently logged in user to profile owner's details.
   
### Changes:

- Change the user query handler from getcurrentUser to getSingleUser.
- Added types for user 
- Changed the query to indexes
- refactored and removed unused import

2024-01-19 06:35 UTC, Sanchitbajaj02 requested changes

2024-01-19 06:35 UTC, Sanchitbajaj02 commented on appwrite-gen/schema.json
> +          "size": 100,
increase about limit to 250 characters.

2024-01-19 06:35 UTC, Sanchitbajaj02 commented on src/components/pages/user/userPosts/index.tsx
> +  userName: string | undefined;
Do we actually need to make userName undefined since it is 100% guranteed that it is stored in user collection

2024-01-19 06:51 UTC, IrfanshaikH-7 commented on src/types/index.d.ts
> +      userLink: Url | null,
You sure - we changed it to URL in data base..

2024-01-19 06:53 UTC, IrfanshaikH-7 commented on src/types/index.d.ts
> +    {
Documents are the arrays - and this is exactly how we are recieving response from the appwrite! If we do a object here we have to create a separate type for rendering out the data ...

2024-01-20 04:29 UTC, IrfanshaikH-7 commented on src/types/index.d.ts
> +    {
@Sanchitbajaj02 could you please elaborate on this. I don't quite understood what you meant by instead of documents.

2024-01-20 13:39 UTC, Sanchitbajaj02 commented on src/types/index.d.ts
> +    {
@IrfanshaikH-7 Upon researching a bit, I am merging this PR but if this module gets into issue, I will ping you to solve this

2024-01-20 14:53 UTC, merged