Random avatar generator for profiles #154
Sanchitbajaj02/palettegram pull request #207
Opened 2024-01-21 11:40 UTC by DaSeeker67

## Related Issue
Random avatar generator for profiles #154

## Description

created the function to generate random avatar from boring avatar during the signup saved the generated link into the db and use the link to show the avatar in the user profile page

## Screenshots

some authentication error

2024-01-21 18:40 UTC, Sanchitbajaj02 requested changes

2024-01-21 18:40 UTC, Sanchitbajaj02 commented on src/backend/avatarGenerator.ts
> +export const generateAvatar = (name: string, variant: string = 'marble', size: number = 120, colors: string[] = []): string => {
Are you sure that once the URL is generated and saved into database, it will be static and not changed?

2024-01-29 09:56 UTC, Manishak798 requested changes
Resolve Merge Conflicts.

2024-02-15 06:57 UTC, Sanchitbajaj02 commented
@DaSeeker67 please resolve the merge conflicts to get this pull request merged

2024-02-17 04:46 UTC, Girishbari commented
@DaSeeker67 do you want any help with this...

2024-02-17 12:13 UTC, Sanchitbajaj02 approved these changes

2024-02-17 19:10 UTC, merged